List<String> letters() {
  return [
    ...List.filled(12, "A"),
    ...List.filled(1, "B"),
    ...List.filled(5, "C"),
    ...List.filled(6, "D"),
    ...List.filled(19, "E"),
    ...List.filled(4, "F"),
    ...List.filled(3, "G"),
    ...List.filled(5, "H"),
    ...List.filled(11, "I"),
    ...List.filled(1, "J"),
    ...List.filled(1, "K"),
    ...List.filled(5, "L"),
    ...List.filled(4, "M"),
    ...List.filled(11, "N"),
    ...List.filled(11, "O"),
    ...List.filled(4, "P"),
    ...List.filled(1, "Q"),
    ...List.filled(12, "R"),
    ...List.filled(9, "S"),
    ...List.filled(13, "T"),
    ...List.filled(4, "U"),
    ...List.filled(1, "V"),
    ...List.filled(2, "W"),
    ...List.filled(1, "X"),
    ...List.filled(3, "Y"),
    ...List.filled(1, "Z"),
  ];
}
